### ISSUE TITLE
NoSuchMethodError:kafka.utils.ZkUtils$.readDataMaybeNull 

### ISSUE THREAD

**Issue by mklzl** [qindongliang/streaming-offset-to-zk#5]
借鉴您的代码，维护kafka的偏移量，程序打包之后，（环境：CDH   kafka0.9（默认），zkclient为0.7   spark2，scala2.11）报错找不到方法
错误如下：
Exception in thread "main" java.lang.NoSuchMethodError: kafka.utils.ZkUtils$.readDataMaybeNull(Lorg/I0Itec/zkclient/ZkClient;Ljava/lang/String;)Lscala/Tuple2;
	at kafkaManager$.readOffset(kafkaManager.scala:22)
	at kafka2HdfsUseZK$.createDirectStream(kafka2HdfsUseZK.scala:68)
	at kafka2HdfsUseZK$.createStreamingContext(kafka2HdfsUseZK.scala:46)
	at kafka2HdfsUseZK$.main(kafka2HdfsUseZK.scala:89)
	at kafka2HdfsUseZK.main(kafka2HdfsUseZK.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
我自己在尝试将这个方法所在jar的kafka0.9 的jar包放入kafka的jar目录，提交指定jar路径，但是依旧报这个错，麻烦告知一下引起这个错误的原因是什么？如何解决？

**Comment by qindongliang** [comment]
你这个应该是zkClient的工具包，版本有问题或者冲突了

**Comment by mklzl** [comment]
确实是冲突问题，我将readDataMayBeNull换为readData方法就可以了
